export const addSection: string
export const listSection: string
export const onBoarding: string
export const onBoardingContainer: string
export const furtnitureCalculator: string
export const bottomSeparator: string
export const topSeparator: string
export const botAlertList: string
export const listTitle: string
export const listHeader: string
export const totalVolume: string
